### ISSUE TITLE
Missing constraints on entry.flag in the profile "List of Medicine Changes from an Event"

### ISSUE THREAD

**Issue by dtr-agency** [AuDigitalHealth/ci-fhir-stu3#1]
# Prerequisites
- [x] I have verified the problem exists in the available content
- [x] I have searched [open](https://github.com/ci-fhir-stu3/Issues/issues) and [closed](https://github.com/ci-fhir-stu3/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [x] I have written a descriptive issue title

# The bug
The profile List of Medicine Changes from an Event (http://ns.electronichealth.net.au/ci/fhir/3.0/StructureDefinition/list-medseventchanges-1) is missing the flag element as must support. It is also missing the intended cardinality constraint of 1..1.

## What I expected to happen
The flag element should be in the Differential table, the cardinality should be displayed as 1..1, there should be a must support flag.

## Steps to reproduce
1. Go to ../ci-fhir-stu3/output/EventSummary/StructureDefinition-list-medseventchanges-1.html
2. Select Snapshot Table
3. Scroll down to element flag and see the errors... no must support flag is visible and cardinality is 0..1

## QA.html excerpt
N/A

## Desktop (please complete the following information):
- OS: Windows 10
- Browser: Chrome
- Date this bug was detected: 25 March 2019

## Additional context
N/A

**Comment by dtr-agency** [comment]
Bug fix created in backlog: https://jira.digitalhealth.gov.au/browse/CIFMM-2341

**Comment by dbojicic-agency** [comment]
Closing via commits
* https://github.com/AuDigitalHealth/ci-fhir-stu3/commit/da5c1de99120b6d0c60bc9610fe1d642e07ce341
* https://github.com/AuDigitalHealth/ci-fhir-stu3/commit/ea4e242ea887300e30003d8ba2c6bf6eeea2155e
