### ISSUE TITLE
Composition Event Summary section.entry invariants need to move to section element

### ISSUE THREAD

**Issue by dtr-agency** [AuDigitalHealth/ci-fhir-stu3#19]
# Prerequisites
- [x] I have verified the problem exists in the available content
- [x] I have searched [open](https://github.com/ci-fhir-stu3/Issues/issues) and [closed](https://github.com/ci-fhir-stu3/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [x] I have written a descriptive issue title

# The bug
Some invariants in Event Summary composition to control section membership are on section.entry. Current agreed design for invariants that control section membership is on the section element.

There is also conflict in presentation of the same rules between Event Summary and Shared Health Summary, e.g. same intended outcome for Medical History but Shared Health Summary has invariants on the section element, and Event Summary has invariants on both section and on section.entry that are intended to do the same thing.

## What I expected to happen
See no invariants on section.entry, have duplicated invariant content across profiles wherever possible. 

## Steps to reproduce
1. Go to ../ci-fhir-stu3/output/EventSummary/StructureDefinition-composition-es-1.html
2. Go to ../ci-fhir-stu3/output/SharedHealthSummary/StructureDefinition-composition-shs-1.html
3. See the differences in invariant positioning and wording but same intended rule:
    * ES has on a section.entry "inv-dh-cmp-04: At least one condition or procedure shall be present, or an assertion that there is no history shall be present, but not both"
    * SHS has on a section "inv-dh-cmp-05: This section shall not contain both summary statement of medical history entries (condition or procedure) and assertion of no relevant finding entries"

## QA.html excerpt
N/A

## Desktop (please complete the following information):
- OS: Windows 10
- Browser: Chrome
- Date this bug was detected: 03 April 2019

## Additional context
See  invariants in StructureDefinition-composition-shs-1 and StructureDefinition-composition-phs-1

**Comment by dtr-agency** [comment]
Created bug fix in backlog: https://jira.digitalhealth.gov.au/browse/CIFMM-2370

**Comment by robeastwood-agency** [comment]
This issue has been closed via acceptance of pull request via commit https://github.com/AuDigitalHealth/ci-fhir-stu3/commit/d2f6c63300516885a0b48e279396a8e140eabc7c
