### ISSUE TITLE
Remove legacy examples from ci-fhir-stu3/examples

### ISSUE THREAD

**Issue by dtr-agency** [AuDigitalHealth/ci-fhir-stu3#22]
# Prerequisites
- [x] I have verified the problem exists in the available content
- [x] I have searched [open](https://github.com/ci-fhir-stu3/Issues/issues) and [closed](https://github.com/ci-fhir-stu3/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [x] I have written a descriptive issue title

# The bug
Some examples have been carried over from the legacy repository and should be removed. For various reasons:
* min examples - no longer the approach
* max examples - no longer the approach
* only demonstrate syntactic content and do not support any meaningful use case
* examples for profiles we don't have any more e.g. location etc.

The examples to be removed (aka deleted) are:

1. examples/device-max-example.xml
2. examples/device-min-example.xml
3. examples/devicepaid-max-example.xml
4. examples/endpoint-example.xml
5. examples/healthcareservice-example.xml
6. examples/humanname-dh-base-example-Max.xml
7. examples/humanname-dh-base-example-Min.xml
8. examples/location-dh-base-example-max.xml
9. examples/location-dh-base-example-min.xml
10. examples/organization-max-example.xml
11. examples/organization-min-example.xml
12. examples/organization-with-identifier-slices-example.xml
13. examples/patient-max-example.xml
14. examples/patient-min-example.xml
15. examples/patient-with-identifier-slices-example.xml
16. examples/relatedperson-base-max-example.xml
17. examples/relatedperson-base-min-example.xml
18. examples/relatedperson-with-identifier-slices-example.xml
19. examples/bundle-gg0gh111a-cc0f-4c3d-a4cd-a35ceafff555-doc.html - this is not legacy but it needs to be removed

## What I expected to happen
...

## Steps to reproduce
N/A

## QA.html excerpt
N/A

## Available workarounds
N/A

## Desktop (please complete the following information):
- OS: Windows 10
- Browser: Chrome
- Date this bug was detected: 05 April 2018

## Additional context
N/A

**Comment by dtr-agency** [comment]
Bug fix created in backlog: https://jira.digitalhealth.gov.au/browse/CIFMM-2373

**Comment by robeastwood-agency** [comment]
This ticket has been closed via commits https://github.com/AuDigitalHealth/ci-fhir-stu3/commit/a9848867f5387db594fe55ff9158bb2b5316e71d and https://github.com/AuDigitalHealth/ci-fhir-stu3/commit/66663b43973bc2349a26d53ec9e7071401a19c2a
