### ISSUE TITLE
Develop Shared Medicines List FHIR IG

### ISSUE THREAD

**Issue by dbojicic-agency** [AuDigitalHealth/ci-fhir-stu3#26]
# Prerequisites
- [x] I have searched [open](https://github.com/ci-fhir-stu3/Issues/issues) and [closed](https://github.com/ci-fhir-stu3/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already requested or reported
- [x] I have written a descriptive issue title

# The issue / feature
## Change description
To create a draft Australian realm implementation guide of the HL7TM FHIR® specification to represent a Shared Medicines List (SML).
 
## What it actually enables people to do
Allows for engagement around exchanging practitioner authored lists of current and pertinent medicines for a patient. Enables trialing implementation of those resources for the usage.

## Mockups 
N/A

## How awesome would it be?
Fairly awesome, this is a high priority work at the moment.

## Workarounds
N/A

## Additional context
N/A

**Comment by dbojicic-agency** [comment]
Currently working on updating existing models to make them reusable across multiple IGs (e.g. AllerguIntolerance, Encounter). Looking to publish the first draft of the IG here by Fri 24th May.

**Comment by dbojicic-agency** [comment]
Working on updating Medication (http://ns.electronichealth.net.au/ci/fhir/3.0/StructureDefinition/medication-known-1; github issue #29) and Encounter (http://ns.electronichealth.net.au/ci/fhir/3.0/StructureDefinition/encounter-es-1; github issue #33) profiles needed for this IG. 
Looking at making the draft available later today/tomorrow.

**Comment by dbojicic-agency** [comment]
Working on improving implementation guidance and creating examples for PSML.

**Comment by dtr-agency** [comment]
Implementation guidance now refactored.

**Comment by dtr-agency** [comment]
https://github.com/AuDigitalHealth/ci-fhir-stu3/commit/0b59b3a8e83febb65eb32bf009d3edebf47ac1ee#diff-04e4e9f92e3509f85d07eb60a94c76cb added new base substance profile for SML.

**Comment by robeastwood-agency** [comment]
Multiple updates made across the draft SML IG; this ticket can be considered closed with further updates to be made by new tickets.
