### ISSUE TITLE
Support exchange of Prescription and Dispense Lists

### ISSUE THREAD

**Issue by dtr-agency** [AuDigitalHealth/ci-fhir-stu3#28]
# Prerequisites
- [X] I have searched [open](https://github.com/ci-fhir-stu3/Issues/issues) and [closed](https://github.com/ci-fhir-stu3/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already requested or reported
- [X] I have written a descriptive issue title

# The issue / feature
## Change description
We need to support the exchange of prescription / dispense lists as a supported meds list usage scenario. We need to decide the appropriate resources, and profile those resources for the usage scenarios:
1. exchange of a list of prescriptions
2. exchange of a list of dispense records
3. exchange of a list of prescriptions and dispense records

## What it actually enables people to do
Allows for engagement around lists, medicines lists, and in particular prescription and dispense lists. Enables trialling implementation of those resources for the usage. Contributes to maturity of the HL7 AU Base Medicines List work and its associated terminology. 

## Mockups 
N/A
## How awesome would it be?
Very awesome - this work contributes to the understanding of how to support medicine lists incl where there are shared concepts or different concepts depending on the usage scenario. 

This work contributes to design comparisons for the forthcoming shared meds list by exploring similar usage scenarios.

This work enables moving towards a 'document optional' scenario where the exchange of contextualised groups of data can occur without forcing a 'document' to be the vehicle.

## Workarounds
N/A

## Additional context
Any 'list' should be able to be derived from AU Medicine List (http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-au-medlist.html)

**Comment by dtr-agency** [comment]
Starting design investigation. Mock-ups to be documented on internal team page: https://confluence.digitalhealth.gov.au/pages/viewpage.action?pageId=106915166

**Comment by dtr-agency** [comment]
Early design investigation complete and documented on the internal team page https://confluence.digitalhealth.gov.au/pages/viewpage.action?pageId=106915166. Three profiles are proposed.

1. A profile of **Composition** to define a representation of a document that may be a Prescription List, or a Dispense List, or a Prescription and Dispense List for a patient in an Australian healthcare context. The author of the document (the Composition) may not be the author of the prescriptions or dispense records.
2. A profile of **List** that may be a Prescription List, or a Dispense List, or a Prescription and Dispense List for a patient in an Australian healthcare context. The source of the list may not be the author of the prescriptions or dispense records. The list may be exchanged in a document or as a standalone list with or without provenance.
3. A profile of **Provenance** to define a representation of provenance record of the creation of a list resource.

A LOINC code to of 57828-6 “Prescription list” is available for use, but there are no corresponding codes to support a dispense record list, or a list that contains prescriptions and dispense records. Two new document codes have been requested for the NCTIS code system. https://healthterminologies.gov.au/fhir/CodeSystem/nctis-data-components-1 to support differentiation at a document code level for the three scenarios.

Roughly the usage at the Composition level is that **when the list is a prescription list**

- The Composition code is expected to be 57828-6 "Prescription list"
- A single section of type Prescription list with the code 57828-6 "Prescription list" is expected
- A list entry is expected
- If the list is generated from a filter or search query a provenance entry is expected

**When the list is a dispense record list**

- The Composition code is expected to be 100.xxxxx "Dispense List"
- A single section of type Prescription list with the code 100.xxxxx "Prescription list" is expected
- A list entry is expected
- If the list is generated from a filter or search query a provenance entry is expected

**When the list is a prescription and dispense list**

- The Composition code is expected to be 100.xxxxx "Prescription and Dispense List"
- It is expected that sections are instantiated as either:
- A single section of type Prescription and dispense list, or 
- Two sections, one of type Dispense list and one of type Prescription list.
- If a section is not empty it is expected that a list entry is referenced
- If the list is generated from a filter or search query a provenance entry is expected

**Comment by dtr-agency** [comment]
Design review in progress.

**Comment by dtr-agency** [comment]
Story to create new IG for Prescription and Dispense Lists in backlog: https://jira.digitalhealth.gov.au/browse/CIFMM-2466

**Comment by dtr-agency** [comment]
Design review complete and documented in confluence. Stories to be added to backlog.

**Comment by dtr-agency** [comment]
Backlog stories for profiles created:
https://jira.digitalhealth.gov.au/browse/CIFMM-2475
https://jira.digitalhealth.gov.au/browse/CIFMM-2476
https://jira.digitalhealth.gov.au/browse/CIFMM-2477

**Comment by dtr-agency** [comment]
https://github.com/AuDigitalHealth/ci-fhir-stu3/commit/b412eb46c3d670707fd7f4fc11294942634445d1 new empty PDL FHIR IG committed. https://jira.digitalhealth.gov.au/browse/CIFMM-2466 is DONE.

**Comment by dtr-agency** [comment]
https://jira.digitalhealth.gov.au/browse/CIFMM-2477 (Provenance profile) in progress by R.Collins

**Comment by dbojicic-agency** [comment]
Work is underway to create a Prescription and or Dispense List Composition profile via https://jira.digitalhealth.gov.au/browse/CIFMM-2475.

**Comment by robeastwood-agency** [comment]
Improvements are being made to the informative narrative as found via the main menu (intro, guidance, downloads etc). Internal Agency ticket: https://jira.digitalhealth.gov.au/browse/CIFMM-3337

**Comment by davidmckillop** [comment]
Known issues are being created for a number of outstanding items.  These issues will be address in R4.
Internal Agency ticket: https://jira.digitalhealth.gov.au/browse/CIFMM-3265

**Comment by robeastwood-agency** [comment]
Improvements have now been made to the informative narrative pages as found via the main menu.

**Comment by davidmckillop** [comment]
Known issue has been added to 'Provenance for the Generation of a List' stating that inv-dh-prov-03 should enforce a reference to a list.

**Comment by robeastwood-agency** [comment]
Updates have been made to all profile intro files with wording improvements, formatting standardisation, reuse of recently updated wording and updated publication status.

**Comment by dbojicic-agency** [comment]
New document codes to support a dispense record list, or a list that contains prescriptions and dispense records have been created in the NCTIS code system https://healthterminologies.gov.au/fhir/CodeSystem/nctis-data-components-1:

- 100.32014 “Dispense List”

- 100.32015 “Prescription and Dispense List”

**Comment by dbojicic-agency** [comment]
Prescription and Dispense List (PDL) FHR IG that supports the  exchange of a list of prescriptions, exchange of a list of dispense records and exchange of a list of prescriptions and dispense records  as a document or as a standalone list is now available. 

PDL implementation guide references:
1.	A profile of Composition (StructureDefinition-composition-pdl-1) to define a representation of a document that may be a Prescription List, or a Dispense List, or a Prescription and Dispense List for a patient in an Australian healthcare context. 
2.	A profile of List (StructureDefinition-list-pdl-1) that may be a Prescription List, or a Dispense List, or a Prescription and Dispense List for a patient in an Australian healthcare context. The list may be exchanged in a document or as a standalone list with or without provenance.
3.	A profile of Provenance (StructureDefinition-provenance-list-gen-1) to define a representation of provenance record of the creation of a list resource.
4.	Other profiles referenced by above profiles (ie a profile of Patient (StructureDefinition-patient-ident-1), necessary to assert conformance.

The profiles that form part of this implementation guide are early designs that demonstrate the intended use (via constraints in a profile or documented known issues that describe the intended use ) and provide implementation guidance for the overarching usage scenarios.

PDL implementation guide is incomplete as it is missing features of other more matured implementation guides in the ci-fhir-stu3 repository, ie examples and references between profiles are missing. 


This implementation guide may transition to FHIR Release 4, in collaboration with HL7 Australia.
