### ISSUE TITLE
Medication profile - remove unneeded must support flags (Known Medicine)

### ISSUE THREAD

**Issue by dtr-agency** [AuDigitalHealth/ci-fhir-stu3#29]
# Prerequisites
- [X] I have searched [open](https://github.com/ci-fhir-stu3/Issues/issues) and [closed](https://github.com/ci-fhir-stu3/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already requested or reported
- [X] I have written a descriptive issue title

# The issue / feature
## Change description
Updating the Known Medicine profile (http://ns.electronichealth.net.au/ci/fhir/3.0/StructureDefinition/medication-known-1) to be more targeted to our usage scenarios. The current version of the profile spams must support flags in lieau an understanding of what might be supported in our expected exchange scenarios. 

Several meetings with multiple internal and external stakeholders have better defined the usage scenarios and identified several elements with must support flags for which there is no expectation of use (or we would prefer are not used).

Suggested to remove must support flags for:
- pbs-sponsor (out of discussion with HL7 it has been decided to remove this from the base HL7 AU profile, this should be supported in manufacturerOrganization not a separate element)
- status (this concept is removed as we have no use case for supporting a discrete Medication that is not referenced by a contextualising resource such as MedicationStatement or MedicationRequest which will carry the meaningful status value)
- package.content and its children (this concept has been removed in R4; we want to maintain alignment with R4; in addition the guidance in HL7 AU Base recommends that content be the same as the medication item... thus this is not a separate concept but defined implicitly by medication.code and would have separate existence)
- package.batch.medication-batch-serialnumber (out of discussion with HL7 it has been decided to remove this extension from the base HL7 AU profile, this was an R4 pre-adoption to ensure alignment between STU3 and R4 and during R4 development this element was removed)

Discussion was had on removing must support on batch however it was agreed that there were some potential usage scenarios relating to dispense, medication tracking, data entry via barcode scanning etc. where these were meaningful.

## What it actually enables people to do
Targeted set of must support reduces noise in documentation, in data, communicates expectations clearer, reduces burden on implementation and support.

## Mockups 
Not done.

## How awesome would it be?
Very amazing - a robust but targeted profile for medication is required for forthcoming shared medications list work. This change helps support that work.

## Workarounds
N/A

## Additional context
Issues with PBSSponsor: https://github.com/hl7au/au-fhir-base/issues/272
Deprecate extension Medication Batch Serial Number (was for R4 preadoption but did not make it to R4 publication): https://github.com/hl7au/au-fhir-base/issues/274
Backlog story: https://jira.digitalhealth.gov.au/browse/CIFMM-2407

**Comment by dtr-agency** [comment]
Updated to include removing must support on Medication.status

**Comment by dbojicic-agency** [comment]
Currently in peer review via backlog story CIFMM-2407.
