### ISSUE TITLE
doseStatus missing MustSupport flag in the profile "Summary Statement of Administered Vaccine "

### ISSUE THREAD

**Issue by dtr-agency** [AuDigitalHealth/ci-fhir-stu3#3]
# Prerequisites
- [x] I have verified the problem exists in the available content
- [x] I have searched [open](https://github.com/ci-fhir-stu3/Issues/issues) and [closed](https://github.com/ci-fhir-stu3/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [x] I have written a descriptive issue title

# The bug
The profile Summary of Administered Vaccine (http://ns.electronichealth.net.au/ci/fhir/3.0/StructureDefinition/immunization-summary-administration-1) is missing the doseStatus element as must support (at this time the design approach is that all mandatory elements are expected to get a must support flag).

## What I expected to happen
The doseStatus element should be in the Differential table with a must support flag. There should also be implementation guidance on what to do with this mandatory element if it isn't present in the authoring system in profile page in the Shared Health Summary IG.

## Steps to reproduce
1. Go to ../ci-fhir-stu3/output/SharedHealthSummary/StructureDefinition-immunization-summary-administration-1.html
2. Select Snapshot Table
3. Scroll down to element doseStatus and see error... no must support flag is visible

## QA.html excerpt
N/A

## Desktop (please complete the following information):
- OS: Windows 10
- Browser: Chrome
- Date this bug was detected: 25 March 2019

## Additional context
N/A

**Comment by dtr-agency** [comment]
Bug fix created in backlog: https://jira.digitalhealth.gov.au/browse/CIFMM-2337

**Comment by dbojicic-agency** [comment]
Closing via above commit.
