### ISSUE TITLE
New feature consideration - recording 'special administration events'

### ISSUE THREAD

**Issue by robeastwood-agency** [AuDigitalHealth/ci-fhir-stu3#31]
# Prerequisites
- [x] I have searched [open](https://github.com/ci-fhir-stu3/Issues/issues) and [closed](https://github.com/ci-fhir-stu3/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already requested or reported
- [x] I have written a descriptive issue title

# The feature
## Change description
There are certain therapeutic interventions that have potentially long-term implications on future care decisions, even long after the intervention has ceased. It is important that these are singled out for future awareness and decision making.

The most common case is medications which can only be administered once or have a cumulative effect where you can’t exceed a maximum dose within lifetime or defined period. This can include some vaccines and particularly immunosuppressants such as Novotrone and Epirubicin. These drug classes are routinely used in chemotherapy, treatment of multiple sclerosis and organ transplants. 
While not a medication administration per se, radiotherapy treatment also has the concept of lifetime dosage limits.  In radiation therapy the dosing units are called monitor units (MU).

Consideration for defining a “Special Administration” clinical data model catering for a range of administrations – i.e. medications, radiation and any others. 

The clinical requirements for this would need to be considered in detail to better understand the use of this data. And then to determine how this content could be put to use.

## What it actually enables people to do
A supporting data model would allow these special administrations to be recorded and highlighted in some form of longitudinal record for future awareness and decision making. 

## Mockups 
None available at this point

## How awesome would it be?
This will have a significant impact upon the safety of a patient in that potentially harmful interventions are avoided.

## Workarounds
N/A

## Additional context
This was originally raised by jurisdictional stakeholders a few years ago, which never progressed past a few emails / discussions etc.

**Comment by robeastwood-agency** [comment]
Originally raised in the internal Agency backlog ticket https://jira.digitalhealth.gov.au/browse/CCP-530

**Comment by dtr-agency** [comment]
This issue has been moved to ci-fhir-r4 - all new work will be R4 going forwards. Now AuDigitalHealth/ci-fhir-r4#2
