### ISSUE TITLE
New implementation guide to support FHIR discharge summary

### ISSUE THREAD

**Issue by robeastwood-agency** [AuDigitalHealth/ci-fhir-stu3#32]
# Prerequisites
- [x] I have searched [open](https://github.com/ci-fhir-stu3/Issues/issues) and [closed](https://github.com/ci-fhir-stu3/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already requested or reported
- [x] I have written a descriptive issue title

# The issue / feature
## Change description
To create a draft Australian realm implementation guide of the HL7® FHIR® specification to represent a discharge summary.

This will entail a specific composition profile and number of supporting profiles, all derived from [HL7 AU profiles](http://build.fhir.org/ig/hl7au/au-fhir-base/profiles.html), where possible. The intent is to support commonly encountered sections in discharge summaries, such as:
- Problems/Diagnoses
- Clinical Interventions
- Allergies and Intolerances
- Medications
- Clinical synopsis
- Alerts
- Arranged services
- Recommendations
- Diagnostic Investigations

## What it actually enables people to do
Exchange discharge summaries using FHIR®-based models. Enables trialing implementation of those resources for the usage.

## Mockups 
N/A

## How awesome would it be?
Discharge summaries are one of the most valued clinical document exchanges and supporting their implementation based on the latest technology (FHIR®) would be quite an achievement.

## Workarounds
N/A

## Additional context
N/A

**Comment by dtr-agency** [comment]
This issue has been moved to ci-fhir-r4 - all new work will be R4 going forwards. Now https://github.com/AuDigitalHealth/ci-fhir-r4/issues/1
