### ISSUE TITLE
Update Event Summary composition to add a rule that the encounter shall have encounter description

### ISSUE THREAD

**Issue by dbojicic-agency** [AuDigitalHealth/ci-fhir-stu3#34]
# Prerequisites
- [X] I have searched [open](https://github.com/ci-fhir-stu3/Issues/issues) and [closed](https://github.com/ci-fhir-stu3/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already requested or reported
- [X] I have written a descriptive issue title

# The issue / feature
## Change description
Updating Event Summary profile (http://ns.electronichealth.net.au/ci/fhir/3.0/StructureDefinition/composition-es-1) to add a rule on the encounter reference that the encounter shall have encounter description. 

## Mockups 
New profile description would look like this:
* derived from HL7 AU Base Composition
* 1..1 meta
  * 1..* meta.profile with one value equal to the profile URL
* 1..1 language with fixed value "en-AU"
* 1..1 composition-author-role Reference(PractitionerRole) and with must support
  * inv-dh-cmp-02: A practitioner role shall conform to PractitionerRole with Practitioner with Mandatory Identifier
* identifier with must support
* status with must support
* type with fixed value  "system":"http://loinc.org",  "34133-9" with must support
* 1..1 subject (Patient with mandatory IHI) with must support
* 1..1 encounter with Reference(Summary of an Encounter for an Event) with must support
  * inv-dh-cmp-13: The encounter shall have encounter description
* date with must support
* 1..1 author (Practitioner with mandatory identifier) with must support
* 0..0 confidentiality
* 1..1 attester (mode='legal',mandatory time and party)
* 1..1 custodian (Organization with mandatory identifier) with must support
* 1..1 section slice "eventOverview" with must support
* 0..1 section slice "allergies" with must support
* 0..1 section slice "medications" with must support
* 0..1 section slice 'medicalHistory' with must support
* 0..1 section slice 'Immunisations' with must support
* 0..1 section slice 'Diagnostic Investigations' with must support

## How awesome would it be?
Very awesome as it improves the re-usability of our Encounter model; it can be shared across multiple models now where some of the constraints from the Encounter model would now be controlled by referencing Composition.

## Workarounds
N/A

## Additional context
N/A

**Comment by dbojicic-agency** [comment]
Added to backlog: https://jira.digitalhealth.gov.au/browse/CIFMM-2419

**Comment by robeastwood-agency** [comment]
This has not been implemented in the STU3 Composition profile, but instead a known issue has been added.
This feature will be a consideration in the R4 version of this profile.

**Comment by robeastwood-agency** [comment]
The known issue added is:
> The design of this profile is incomplete. This profile is missing an invariant to mandate the inclusion of Encounter.extension:encounterDescription.

**Comment by davidmckillop** [comment]
This issue has also been accepted as known issues for the composition profile provenance-list-gen-1. STU3 work has been ceased and any future work will continue with R4.
