### ISSUE TITLE
Event Summary - improve implementation guidance esp around lists and medicine changes

### ISSUE THREAD

**Issue by dtr-agency** [AuDigitalHealth/ci-fhir-stu3#35]
# Prerequisites
- [X] I have searched [open](https://github.com/ci-fhir-stu3/Issues/issues) and [closed](https://github.com/ci-fhir-stu3/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already requested or reported
- [X] I have written a descriptive issue title

# The issue / feature
## Change description
Currently very little information providing guidance on how to include the list of medicines, and how to use the available elements to describe changes in medicines.

## What it actually enables people to do
Enables consistent implementation and coding of the data across systems, improves ability to process. Provides clarification of how to support the expected usage scenarios.

## Mockups 
Current thinking around some draft guidance is the following.

*List profile usage guidance*
Replace the following part of the guidance:

> * All medicine items relevant to an event should be included in the list:
>   * For existing unchanged medicine items, the flag will be ‘unchanged’ and change description is not expected to be provided.
>   * For new and changed medicine items, change description is expected to be provided.
> 

With this additional material:

* All medicine items relevant to an event should be included in the list.
* An existing unchanged medicine item should be represented with the flag of 'nochange' and no change-description.
* A recommendation to make a change including cessation, prescription, or dose change should be represented with a recommendation flag, e.g. 'prescription-recommended' or 'review-recommended', and the change-description should describe the proposed change and reason for recommendation.
* A medicine item introduced during this event should be represented with the flag of 'new' or 'prescribed' as appropriate, and a change-description supplied that provides the reason for introduction of the medicine item.
* A change to a medicine item during this event should be represented with the flag of 'amended' and a change-description supplied that describes the change e.g. dose, form, route, frequency.
* A medicine item ceased during this event should be represented with the flag of 'ceased', 'suspended', or 'cancelled' as appropriate, and a change-description supplied that provides the reason for ceasing the medicine item. If a medicine item is no longer actively taken as the prescribed course has been completed this should have the flag 'ceased'.

*MedicationStatement profile usage guidance*
Add the following material to existing guidance
* MedicationStatement status should be consistent with the value of List flag:
  * A medicine item ceased during this event should be represented with a status of 'stopped' or 'completed'; including where a medicine item is no longer actively taken as the prescribed course has been completed.
  * A medicine item introduced during this event should be represented with a status of 'intended'.
  * An existing unchanged medicine item should be represented with a status of 'active' or 'completed' depending if the patient is currently (active) taking the medicine item.
  * A medicine item changed during this event should be represented with a status of 'active'.
  * A recommendation to make a change may not directly result in a similar status unless it is a recommendation to introduce a medicine item. The status should represent the current state of the medicine item for the patient (active, completed, new) not the recommendation.
* MedicationStatement taken should be consistent with the value of List flag:
   * medicine item that has not yet been taken or has never been taken should be represented with taken 'n'.
  * medicine item the patient is currently taking or has taken should be represented with taken 'y'.

## How awesome would it be?
Magnificently awesome, fully necessary, and expected to be required to ensure a shared understanding of the representation, exchange, processing of changed medicines information.

## Workarounds
N/A

## Additional context
Any guidance should be consistent with that in the [HL7 AU Base Medicine List](http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-au-medlist.html) and [AU Base Medication Statement](http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-au-medicationstatement.html).
Backlog story: https://jira.digitalhealth.gov.au/browse/CIFMM-2344

**Comment by LB-Agency** [comment]
These magnificently awesome changes have been made and this issue can now be resolved.
