### ISSUE TITLE
Remove must support flags from the prohibited elements (in line with the revised approach on the use of must support flags in Agency profiles)

### ISSUE THREAD

**Issue by dbojicic-agency** [AuDigitalHealth/ci-fhir-stu3#40]
# Prerequisites
- [x] I have searched [open](https://github.com/ci-fhir-stu3/Issues/issues) and [closed](https://github.com/ci-fhir-stu3/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already requested or reported
- [x] I have written a descriptive issue title

# The issue / feature
## Change description
The must support flag is used to indicate that an element must be supported, how that element must be supported shall be defined. The must support flag cannot be relaxed in profiles that claim to be derived from or conformant to. 

There is a conflict between our definition of must support and elements with cardinality of 0..0 - it is impossible to satisfy both. That use of must support has been to represent 'modelling practice' rather than serving to provide implementation rules - the overlap is significant; it is only where the prohibition is in place that there is divergence between the two ends.

Our approach had been that we place a must support flag on every concept that we agree makes up a base concept of the resource - aka every element that has a real world counterpart. e.g. a patient in the real world has photos so we put a must support on it as we agree this is part of the base concept we have adopted of a patient.

This approach has now been revised to only use must support flag in a profile to serve implementation of that profile, which really is the point of the flag: 
* in Agency Base profiles (e.g. Base Patient): Flag all elements that are required to support the known use cases / usage scenarios for which the profile is designed
* in Agency use case profiles: set on the necessary and sufficient set of elements in a resource that are required to support the known use cases / usage scenarios for which the profile is designed

This means must support flag should be removed from the prohibited elements in the following * Composition Personal Health Notes profile  (composition-phn-1) 
* Base Patient profile (patient-dh-base-1) 
* Use case Patient profile (patient-ident-1) 
* Use case Patient profile (patient-ihi-1)
* Base Practitioner profile (practitioner-dh-base-1) 
* Use case Practitioner profile (practitioner-hpii-1)
* Use case Practitioner profile (practitioner-ident-1)
* Use RelatedPerson profile (relatedperson-dh-base-1) 
* Use case RelatedPerson profile (relatedperson-ident-1)
* Use case RelatedPerson profile (relatedperson-ihi-1) 

## What it actually enables people to do
It enables clear understanding on the level of support by the systems composing and processing resources conformant to the Agency profils.

## Mockups 
N/A

## How awesome would it be?
Pretty awesome, fully necessary, and enables shared understanding of the meaning of must support flags for the implementations.

## Additional context
This is in line with the decision log item: [Updated: Use of Must Support flags in Agency profiles](https://confluence.digitalhealth.gov.au/display/CIN/Updated%3A+Use+of+Must+Support+flags+in+Agency+profiles)
Backlog story: https://jira.digitalhealth.gov.au/browse/CIFMM-2656

**Comment by dtr-agency** [comment]
https://github.com/AuDigitalHealth/ci-fhir-stu3/commit/69c6972b7b79d5da8d0bf6afc9bf61657dcbfc0c for Practitioner profile fixes. https://github.com/AuDigitalHealth/ci-fhir-stu3/commit/40df418aaee5fc2fd5c773b8867e690618ab74cd for RelatedPerson fixes.
