### ISSUE TITLE
Medication instance errors when conforming to medication-dh-base-1 profile

### ISSUE THREAD

**Issue by robeastwood-agency** [AuDigitalHealth/ci-fhir-stu3#47]
# Prerequisites

- [x] I have verified the problem exists in the available content
- [x] I have searched [open](https://github.com/ci-fhir-stu3/Issues/issues) and [closed](https://github.com/ci-fhir-stu3/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [x] I have written a descriptive issue title

# The bug
All Medication resource instances that are attempting to conform to the Agency [medication-dh-base-1 profile](https://github.com/AuDigitalHealth/ci-fhir-stu3/blob/master/resources/medication-dh-base-1.xml) are raising numerous QA report errors which cannot currently be resolved, in the context of Agency FHIR IGs. The errors are related to the `Medication.code` element and the source of the errors has been traced back to the HL7 AU [AU Base Medication profile](https://build.fhir.org/ig/hl7au/au-fhir-base-stu3/StructureDefinition-au-medication.html), from which the Agency profile has been derived. It is understood that the issue may be related to the invariant FHIRPath expressions that constrain the `Medication.code` element.
For reference, the QA report for the SML IG can be found [here](https://github.com/AuDigitalHealth/ci-fhir-stu3/blob/master/output/SharedMedicinesList/qa.html).

## What I expected to happen
No errors would be raised for all Medication instances attempting to conform to the Agency [medication-dh-base-1 profile](https://github.com/AuDigitalHealth/ci-fhir-stu3/blob/master/resources/medication-dh-base-1.xml).

## Steps to reproduce
1. Run the IG publisher on one of the Agency IGs containing Medication instances (ie SML)
2. Open the qa.html file (linked above) in the output folder
3. Scroll down to Medication instances
4. See multiple errors

## Screenshots
n/a

## Workarounds
n/a

## QA.html excerpt
```
Element: Medication/19ae06e9-0242-41eb-b386-5c147b01e88f: Medication.code
Error: AMT TPUU valueset membership required [coding.where((system = 'http://snomed.info/sct') and (extension.where(url = 'http://hl7.org.au/fhir/CodeSystem/medication-type').valueCoding = 'BPDSF')).exists() implies coding.where((system = 'http://snomed.info/sct') and (extension.where(url = 'http://hl7.org.au/fhir/CodeSystem/medication-type').valueCoding = 'BPDSF')).first().code in 'http://hl7.org.au/fhir/ValueSet/amt-tpuu-codes']
```

## Desktop (please complete the following information):
n/a

## Additional context
n/a

**Comment by dtr-agency** [comment]
https://github.com/hl7au/au-fhir-base-stu3/issues/10

**Comment by dtr-agency** [comment]
https://github.com/hl7au/au-fhir-base-stu3/issues/9
https://github.com/hl7au/au-fhir-base-stu3/issues/6

**Comment by robeastwood-agency** [comment]
The resolvable medication errors have now been fixed as a result of the accepted pull request on the HL7 AU Base medication (https://github.com/hl7au/au-fhir-base-stu3/pull/13).
