### ISSUE TITLE
Incorrect use of fixedCodeableConcept in various profiles

### ISSUE THREAD

**Issue by robeastwood-agency** [AuDigitalHealth/ci-fhir-stu3#48]
# Prerequisites

- [x] I have verified the problem exists in the available content
- [x] I have searched [open](https://github.com/ci-fhir-stu3/Issues/issues) and [closed](https://github.com/ci-fhir-stu3/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [x] I have written a descriptive issue title

# The bug
Attempts to fix the value of system and code in CodeableConcept elements are incorrectly using fixedCodeableConcept directly on the CodeableConcept element. The result of this prohibits CodeableConcept.text and CodeableConcept.coding.display (as well as other elements), which will inhibit the representation of realistic instances of data.
This is apparent in the following profiles:
- composition-sml-prac-1  (resolved as known issue)
- composition-acdcr-1 (fixed)
- composition-acp-1 (fixed)
- composition-es-1   (resolved as known issue)
- composition-phn-1  (fixed)
- composition-phs-1   (fixed)
- composition-shs-1  (fixed)
- documentreference-acp-1
- list-medseventchanges-1   (resolved as known issue)
- provenance-list-gen-1   (resolved as known issue)

## What I expected to happen
The fixed values are present as expected without prohibiting other useful elements.

## Workarounds
None

## Desktop (please complete the following information):
- N/A

## Additional context
Wherever possible, use [ElementDefinition.pattern[x]](http://hl7.org/fhir/R4/elementdefinition-definitions.html#ElementDefinition.pattern_x_) for specifying values of CodeableConcept and Coding type elements.

**Comment by richardtownleyoneill-ADHA** [comment]
This issue is accepted as a known issue for composition-sml-prac-1 due to project constraints in accordance with the following requirements:
* the minimum normative parts of the code are enforced appropriately
* while not desired, a system can process this data with only the minimum normative parts
Known issue added in https://github.com/AuDigitalHealth/ci-fhir-stu3/commit/74ab468f3426f3f6a2a7fb3c63ac55d24f4abbd1#diff-0c3a887c600181a92b738f7c87f57860

**Comment by LB-Agency** [comment]
This issue is accepted as a known issue for **list-medseventchanges-1** in accordance with the following requirements:

- the minimum normative parts of the code are enforced appropriately
- while not desired, a system can process this data with only the minimum normative parts

**Comment by robeastwood-agency** [comment]
This issue has also been accepted as known issues for the composition profile `composition-es-1`. STU3 work has been ceased and any future work will continue with R4.

Note that 7 known issues were added, one for each of the affected elements.

**Comment by robeastwood-agency** [comment]
Closed in error (as this still affects other profiles)

**Comment by dbojicic-agency** [comment]
Updated Composition Shared Health Summary to fix values of all CodeableConcept elements by using patternCodeableConcept rather than fixedCodeableConcept. This allows  an instance to include extra elements including repetitions (multiple codings).

**Comment by davidmckillop** [comment]
This issue has also been accepted as known issues for the composition profile provenance-list-gen-1. STU3 work has been ceased and any future work will continue with R4.

**Comment by davidmckillop-ADHA** [comment]
Created known issues of Provenance for the Generation of a List profile for the CodeableConcept elements of activity, agent:assemblingDevice.role and agent:All Slices,

**Comment by dbojicic-agency** [comment]
Work has commenced to fix values of all CodeableConcept elements in Personal Health Summary Composition profile (StructureDefinition-composition-phs-1) by using patternCodeableConcept rather than fixedCodeableConcept.

**Comment by dbojicic-agency** [comment]
Updated Composition Personal Health Summary to fix values of all CodeableConcept elements by using patternCodeableConcept rather than fixedCodeableConcept. This allows an instance to include extra elements including repetitions (multiple codings).

**Comment by davidmckillop-ADHA** [comment]
Updated Composition Personal Health Notes (composition-phn-1) to fix values of all CodeableConcept elements by using patternCodeableConcept rather than fixedCodeableConcept. This allows an instance to include extra elements including repetitions (multiple codings).

**Comment by dbojicic-agency** [comment]
Work is in progress to address this issue in the Advance Care Planning Document Reference (StructureDefinition-documentreference-acp-1) profile. In this profile existing DocumentReference.type fixed value will be replaced by a terminology binding to a value set that allows for subtypes of the advance care planning document.

**Comment by dbojicic-agency** [comment]
Advance Care Planning Document Reference (StructureDefinition-documentreference-acp-1) profile has now been updated to remove the fixed value from `DocumentReference.type`; instead, the element is now bound to a value set to allow for different types.

**Comment by SatyaYelisetti** [comment]
Work is in progress to address this issue in the Advance Care Planning Composition (StructureDefinition-composition-acp-1) profile. In this profile existing Composition.type and Composition.section.code fixedCodeableConcept will be replaced by patternCodeableConcept.

**Comment by SatyaYelisetti** [comment]
Advance Care Planning Composition.type and Composition.section.code fixedCodeableConcept have been replaced by patternCodeableConcept and the profile is now out for review.

**Comment by SatyaYelisetti** [comment]
Advance Care Planning Composition.type and Composition.section.code fixedCodeableConcept have been replaced by patternCodeableConcept via commit a3eff3d .

**Comment by richardtownleyoneill-ADHA** [comment]
Advance Care Directive Custodian Record Composition.type and Composition.section.code fixed value have been replaced by required pattern via commit ca46530
