### ISSUE TITLE
Update profiles from 3.0.1 to 3.0.2

### ISSUE THREAD

**Issue by richardtownleyoneill-ADHA** [AuDigitalHealth/ci-fhir-stu3#49]
# Prerequisites
- [x] I have searched [open](https://github.com/ci-fhir-stu3/Issues/issues) and [closed](https://github.com/ci-fhir-stu3/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already requested or reported
- [x] I have written a descriptive issue title

# The issue / feature
## Change description
Change the profiles and supporting files to use R 3.0.2 instead of 3.0.1

## What it actually enables people to do
- use the newer version of STU3 with its technical corrections
- continue to use the igPublisher (it no longer works with R 3.0.1)

## How awesome would it be?
Avoid known issues with R 3.0.1, continue producing FHIR IGs. 

## Workarounds
None.

## Additional context
https://chat.fhir.org/#narrow/stream/179165-committers/topic/Technical.20Corrections
https://chat.fhir.org/#narrow/stream/179165-committers/topic/R.24.20Technical.20Correction.20now.20open.20for.20review

**Comment by SatyaYelisetti** [comment]
This is now fixed via 57f06fb8de28dcb6cc9bcab662b88ac4829e5a96

**Comment by SatyaYelisetti** [comment]
reviewed and merged into master

**Comment by dtr-agency** [comment]
Also linked to https://github.com/AuDigitalHealth/ci-fhir-stu3/commit/505a070b08b3719333133e3d0bca3e6e4deec13d#diff-b51cec9755b713dc7920d3010f412911

Completed via https://jira.digitalhealth.gov.au/browse/CIFMM-3080
