### ISSUE TITLE
Need 'complete' Event Summary examples

### ISSUE THREAD

**Issue by dtr-agency** [AuDigitalHealth/ci-fhir-stu3#5]
# Prerequisites
- [x] I have searched [open](https://github.com/ci-fhir-stu3/Issues/issues) and [closed](https://github.com/ci-fhir-stu3/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already requested or reported
- [x] I have written a descriptive issue title

# The issue / feature
## Change description
Need a set of examples that demonstrate reasonable instances for Event Summary. Should also demonstrate some different reference resources, and have some differentiation in content.

## What it actually enables people to do
Demonstrates implementation guidance and usage scenarios, supports implementation in FHIR in general and of the Event Summary implementation guide.

## Mockups 
N/A

## How awesome would it be?
Very awesome! Without any 'complete' Event Summary examples it is difficult to get a sense of the intended outcomes of the specification.

Demonstrates alignment with FHIR-based CDA where the 'same' example is presented in both the FHIR IG and the CDA-IG.

## Workarounds
N/A

## Additional context
N/A

**Comment by dtr-agency** [comment]
Stories in CI backlog to provide three examples in two referencing flavours:
https://jira.digitalhealth.gov.au/browse/CIFMM-2318
https://jira.digitalhealth.gov.au/browse/CIFMM-2319
https://jira.digitalhealth.gov.au/browse/CIFMM-2320
https://jira.digitalhealth.gov.au/browse/CIFMM-2455

**Comment by dtr-agency** [comment]
https://jira.digitalhealth.gov.au/browse/CIFMM-2318 in review

**Comment by dtr-agency** [comment]
https://jira.digitalhealth.gov.au/browse/CIFMM-2319 in review

**Comment by dtr-agency** [comment]
https://jira.digitalhealth.gov.au/browse/CIFMM-2319 on hold

**Comment by dtr-agency** [comment]
1st round of review of example 3 performed.

**Comment by SatyaYelisetti** [comment]
The latest commit (a partial fix) has added new examples (CIFMM-2320) and this issue remains open until CIFMM-2319 and CIFMM-2455 are completed.

**Comment by SatyaYelisetti** [comment]
The latest commit fixed bugs (CIFMM-2468) in the newly added examples (CIFMM-2320) and this issue remains open until CIFMM-2319 and CIFMM-2455 are completed.

**Comment by dtr-agency** [comment]
Please stop adding in the phrase fixes when referring to this ticket.

**Comment by dtr-agency** [comment]
https://jira.digitalhealth.gov.au/browse/CIFMM-2319 in progress with @robeastwood-agency

**Comment by robeastwood-agency** [comment]
With this 3rd example now added into the repository, this ticket is being marked as 'complete'. Further work will be to convert this FHIR example into its CDA counterpart.
