### ISSUE TITLE
SHS Composition profile has bug in invariant for AuthorRole extension

### ISSUE THREAD

**Issue by robeastwood-agency** [AuDigitalHealth/ci-fhir-stu3#54]
# Prerequisites
- [x] I have verified the problem exists in the available content
- [x] I have searched [open](https://github.com/ci-fhir-stu3/Issues/issues) and [closed](https://github.com/ci-fhir-stu3/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [x] I have written a descriptive issue title

# The bug
In the Shared health Summary composition profile (composition-shs-1), the invariant on the mandatory extension Composition.extension:compositionAuthorRole has a faulty FHIRPath expression. The consequence of which is that acceptable content for this element always fails to be valid against these invariants.

The invariant is inv-dh-cmp-09: "A practitioner role shall conform to PractitionerRole with Practitioner with Mandatory Identifier" with the FHIRPath expression of
```
Composition.extension('http://hl7.org.au/fhir/StructureDefinition/composition-author-role').resolve().conformsTo('http://ns.electronichealth.net.au/ci/fhir/3.0/StructureDefinition/practitionerrole-withpractitionerident-1')
```
The following 7 existing examples in the SHS FHIR IG are affected by this FHRPath:
- bundle-205fcc4b-baf2-4683-a48f-b087a5937230.xml
- composition-bd06e981-ba86-4020-ba59-cd89f80e8712.xml
- composition-c53c6c39-3e1a-4038-9ad5-25be8c54481f.xml
- composition-de5ef077b-cc0f-4c3d-a4cd-a35ceafff331.xml
- composition-e-f1412590-54f5-11e9-b475-0800200c9a66.xml
- composition-f-ba3eaa80-55c8-11e9-b475-0800200c9a66.xml
- composition-ff0gh111a-cc0f-4c3d-a4cd-a35ceafff999.xml

## What I expected to happen
Acceptable content for this element shall be valid against these invariants.
Unacceptable content for this element shall not be valid against these invariants.

## The fix
The correct (and simplified) FHIRPath is:
```
extension('http://hl7.org.au/fhir/StructureDefinition/composition-author-role').valueReference.reference.resolve().conformsTo('http://ns.electronichealth.net.au/ci/fhir/3.0/StructureDefinition/practitionerrole-withpractitionerident-1') or extension('http://hl7.org.au/fhir/StructureDefinition/composition-author-role').valueReference.identifier.where(system.count() + value.count() &gt;1).exists()
```

## Screenshots
N/A

## Workarounds
N/A

## QA.html excerpt
N/A

## Desktop (please complete the following information):
N/A

## Additional context
N/A

**Comment by dbojicic-agency** [comment]
Work is underway to fix this invariant bug.

**Comment by dbojicic-agency** [comment]
Invariant inv-dh-cmp-09 has been moved from `Composition.extension:compositionAuthorRole` to the root `Composition` level and updated to include rules on Reference data type (related to [Shared Health Summary composition profile - missing constraints on elements with a Reference #62](https://github.com/AuDigitalHealth/ci-fhir-stu3/issues/62)).

The updated invariant details are: 
> **key**: **inv-dh-cmp-09**: 
> **Description**: The author role shall at least have a reference that conforms to PractitionerRole with Practitioner with Mandatory Identifier or an identifier with at least a system and a value
> **expression**: extension('http://hl7.org.au/fhir/StructureDefinition/composition-author-role').valueReference.reference.resolve().conformsTo('http://ns.electronichealth.net.au/ci/fhir/3.0/StructureDefinition/practitionerrole-withpractitionerident-1') or extension('http://hl7.org.au/fhir/StructureDefinition/composition-author-role').valueReference.identifier.where(system.count() + value.count() >1).exists()
