### ISSUE TITLE
Advance Care Planning Composition profile has bugs in 2 invariants using FHIRPath 'conformsTo'

### ISSUE THREAD

**Issue by robeastwood-agency** [AuDigitalHealth/ci-fhir-stu3#57]
# Prerequisites
- [x] I have verified the problem exists in the available content
- [x] I have searched [open](https://github.com/ci-fhir-stu3/Issues/issues) and [closed](https://github.com/ci-fhir-stu3/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [x] I have written a descriptive issue title

# The bug
In the Advance Care Planning composition profile (composition-acp-1), the invariants on the following 2 extensions have faulty FHIRPath expressions, related to the use of 'conformsTo'. The consequence of which is that acceptable content for these elements always fails to be valid against these invariants.

### 1) Element: Composition.extension:compositionAuthorRole
- key: inv-dh-cmp-04
- Description: A practitioner role shall conform to PractitionerRole with Practitioner with Mandatory Identifier
- FHIRpath expression: `Composition.extension('http://hl7.org.au/fhir/StructureDefinition/composition-author-role').resolve().conformsTo('http://ns.electronichealth.net.au/ci/fhir/3.0/StructureDefinition/practitioner-ident-1')` 
### 2) Element: Composition.attester.extension:attesterRelatedParty
- key: inv-dh-cmp-05
- Description: A related party shall conform to RelatedPerson with Mandatory Identifier
- FHIRpath expression: `Composition.attester.extension('http://hl7.org.au/fhir/StructureDefinition/attester-related-party').resolve().conformsTo('http://ns.electronichealth.net.au/ci/fhir/3.0/StructureDefinition/relatedperson-ident-1')`  |

## What I expected to happen
Acceptable content for this element shall be valid against these invariants.
Unacceptable content for this element shall not be valid against these invariants.

## The fix
The correct (and simplified) FHIRPath is (respectively):
```
valueReference.reference.resolve().conformsTo('http://ns.electronichealth.net.au/ci/fhir/3.0/StructureDefinition/practitioner-ident-1')
valueReference.reference.resolve().conformsTo('http://ns.electronichealth.net.au/ci/fhir/3.0/StructureDefinition/relatedperson-ident-1')

```

## Screenshots
N/A

## Workarounds
N/A

## QA.html excerpt
N/A

## Desktop (please complete the following information):
N/A

## Additional context
N/A

**Comment by SatyaYelisetti** [comment]
Work is in progress to check if that invariants have relative FHIRPath.

**Comment by SatyaYelisetti** [comment]
The invariants have now been changed to have relative paths and are now under review.

**Comment by SatyaYelisetti** [comment]
Changes to the FHIRpath can now be found in the above commit of the structure definition.
