### ISSUE TITLE
Composition (Shared Medicines List Authored by Practitioner) has bug in the information-recipient invariant that prohibits a device

### ISSUE THREAD

**Issue by robeastwood-agency** [AuDigitalHealth/ci-fhir-stu3#59]
# Prerequisites

- [x] I have verified the problem exists in the available content
- [x] I have searched [open](https://github.com/ci-fhir-stu3/Issues/issues) and [closed](https://github.com/ci-fhir-stu3/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [x] I have written a descriptive issue title

# The bug
One invariant on the optional extension **Composition.extension:informationRecipient** has faulty FHIRPath expression. The consequence of which is that unacceptable content for this element is always valid against this invariant.

The affected invariant is:
- inv-dh-cmp-12: An information recipient shall not be a device

With the FHIRath expression:
```
resolve().where($this is Device).exists().not()
```

## What I expected to happen
Acceptable content for this element shall be valid against these invariants.
Unacceptable content for this element shall not be valid against these invariants.

## The fix
Verification of this FHIRPath pattern with targeted examples, conclude that the FHIRPath that works is of this pattern:
```
valueReference.reference.resolve().where($this is Device).exists().not()
```

## Workarounds
Providing a logical reference via identifier rather than a reference to a resource.

**Comment by richardtownleyoneill-ADHA** [comment]
This issue is accepted as a known issue due to project constraints in accordance with the following requirements:
- this is not a mandatory element;
- there is a functioning workaround
- this content is not expected in the PSML use case

This behavior is accepted as a known issue and documented in the SML FHIR IG via: 2bacc4b#diff-0c3a887c600181a92b738f7c87f57860

**Comment by dbojicic-agency** [comment]
Later versions of IG Publisher have been updated and the content validation works as expected when correct FHIRPath expressions are provided. As a result inv-dh-cmp-12 FHIRPath expressions has been updated to:
`valueReference.reference.resolve().where($this is Device).exists().not()`
