### ISSUE TITLE
Event Summary composition profile - missing constraints on elements with a Reference

### ISSUE THREAD

**Issue by dtr-agency** [AuDigitalHealth/ci-fhir-stu3#61]
# Prerequisites
- [X] I have searched [open](https://github.com/ci-fhir-stu3/Issues/issues) and [closed](https://github.com/ci-fhir-stu3/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already requested or reported
- [X] I have written a descriptive issue title

# The issue / feature
## Change description
The Event Summary Composition is missing constraints on elements with a logical type of Reference. 

Without a constraint on Reference there is a wide range of values that are accepted as passing validation, some of which are undesirable. For example,
* the Composition.subject element has the References constrained to profiles that enforce a Patient.identifier - it is intended the subject always has an identifier. 
* if no further constraint is placed on Reference then a subject with only a display or an extension is allowed - more permissible than we intend.

Add constraints on Composition elements of type Reference where additional constraints are desired for the use case:

This is expected to be:
* constraining the cardinality of each Composition.section.entry.reference to be 1..1
* constraining the cardinality of each Composition.encounter.reference to be 1..1
* Adding invariants at the Composition element for:
   * Composition.subject to enforce a reference or an identifier with a system and a value
   * Composition.author to enforce a reference or an identifier with a system and a value
   * Composition.custodian to enforce a reference or an identifier with a system and a value
   * Composition.attester(legalAttester) to enforce a reference or an identifier with a system and a value

## What it actually enables people to do
Enables consistent implementation and validation of meaningful data that serves the use case. Provides clarification of how to support the expected usage scenarios.

## Mockups 
Not available.

## How awesome would it be?
Highly desirable - the design is incomplete without these constraints. This issue must addressed at some stage prior to release for implementation.

## Workarounds
This missing design feature may be addressed in the STU3 profile by documentation of a known issue rather than adding invariants to the Composition. Or possibly a mix of both, addition of some invariants / constraints and a known issue covering off the other invariants not included in the STU3 profile.
Example known issue content

| Reference | Description | Issue No. |
| ------------- | ------------- | ------------- |
| subject | The design of this element is incomplete. In the future it is intended subject shall be constrained to at least have a reference or an identifier with at least a system and a value. | See [ci-fhir-stu3/issues/61](https://github.com/AuDigitalHealth/ci-fhir-stu3/issues/61)  |
|attester (legal) party | The design of this slice is incomplete. In the future it is intended party.Reference shall be constrained to at least have a reference or an identifier with at least a system and a value. | See [ci-fhir-stu3/issues/61](https://github.com/AuDigitalHealth/ci-fhir-stu3/issues/61) |

## Additional context
composition-sml-prac-1 is an example of a Composition with these constraints in place including functioning FHIRPath expression.

**Comment by robeastwood-agency** [comment]
Work is underway to implement a number of additional constraints in the composition profile to better define reference elements, as described above.

**Comment by robeastwood-agency** [comment]
This has been implemented via https://github.com/AuDigitalHealth/ci-fhir-stu3/commit/8fa64c59e0002fe6af45a11cb617eaef4f94740e

Specifically, this was addressed in 2 ways:
1. Adding a cardinality constraint of 1..1 on the reference element of these elements:
   1. Composition.encounter
   1. Composition.section:eventOverview.entry
   1. Composition.section:allergies.entry
   1. Composition.section:medications.entry
   1. Composition.section:medicalHistory.entry
   1. Composition.section:immunisations.entry
1. Adding invariants on the following elements to ensure quality content in references:
    1. Composition: The author role shall at least have a reference that conforms to PractitionerRole with Practitioner with Mandatory Identifier or an identifier with at least a system and a value
    1. Composition: The author shall at least have a reference or an identifier with at least a system and a value
    1. Composition: The custodian shall at least have a reference or an identifier with at least a system and a value
    1. Composition: The subject shall at least have a reference or an identifier with at least a system and a value
    1. Composition.attester:legal: The party shall at least have a reference or an identifier with at least a system and a value
