### ISSUE TITLE
Personal Health Summary composition profile - missing constraints on elements with a Reference

### ISSUE THREAD

**Issue by dtr-agency** [AuDigitalHealth/ci-fhir-stu3#66]
# Prerequisites
- [X] I have searched [open](https://github.com/ci-fhir-stu3/Issues/issues) and [closed](https://github.com/ci-fhir-stu3/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already requested or reported
- [X] I have written a descriptive issue title

# The issue / feature
## Change description
The Personal Health Summary Composition is missing constraints on elements with a logical type of Reference. 

Without a constraint on Reference there is a wide range of values that are accepted as passing validation and is more permissible than we intend.

Add constraints on Composition elements of type Reference where additional constraints are desired for the use case:

This is expected to be:
* constraining the cardinality of each Composition.section.entry.reference to be 1..1

## What it actually enables people to do
Enables consistent implementation and validation of meaningful data that serves the use case. Provides clarification of how to support the expected usage scenarios.

## Mockups 
Not available.

## How awesome would it be?
Highly desirable - the design is incomplete without these constraints. This issue must addressed at some stage prior to release for implementation.

## Workarounds
N/A

...

## Additional context
composition-sml-prac-1 is an example of a Composition with these constraints in place.

**Comment by dbojicic-agency** [comment]
Work has commenced to add missing reference constraints on two section.entry elements.

**Comment by dbojicic-agency** [comment]
Work on this profile has been completed; both sections now mandate  Composition.section.entry.reference.
