### ISSUE TITLE
Consumer Entered Information Document Header composition profile - missing constraints on elements with a Reference

### ISSUE THREAD

**Issue by dtr-agency** [AuDigitalHealth/ci-fhir-stu3#67]
# Prerequisites
- [X] I have searched [open](https://github.com/ci-fhir-stu3/Issues/issues) and [closed](https://github.com/ci-fhir-stu3/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already requested or reported
- [X] I have written a descriptive issue title

# The issue / feature
## Change description
The Consumer Entered Information Document Header Composition is missing constraints on elements with a logical type of Reference. 

Without a constraint on Reference there is a wide range of values that are accepted as passing validation, some of which are undesirable. For example,
* the Composition.subject element has the References constrained to profiles that enforce a Patient.identifier - it is intended the subject always has an identifier. 
* if no further constraint is placed on Reference then a subject with only a display or an extension is allowed - more permissible than we intend.

Add constraints on Composition elements of type Reference where additional constraints are desired for the use case:

This is expected to be:
* Adding invariants at the Composition element for:
   * Composition.subject to enforce a reference or an identifier with a system and a value
   * Composition.author to enforce a reference or an identifier with a system and a value
   * Composition.custodian to enforce a reference or an identifier with a system and a value

## What it actually enables people to do
Enables consistent implementation and validation of meaningful data that serves the use case. Provides clarification of how to support the expected usage scenarios.

## Mockups 
Not available.

## How awesome would it be?
Highly desirable - the design is incomplete without these constraints. This issue must addressed at some stage prior to release for implementation.

## Workarounds
This missing design feature may be addressed in the STU3 profile by documentation of a known issue rather than adding invariants to the Composition. Or possibly a mix of both, addition of some invariants / constraints and a known issue covering off the other invariants not included in the STU3 profile.
Example known issue content

| Reference | Description | Issue No. |
| ------------- | ------------- | ------------- |
| subject | The design of this element is incomplete. In the future it is intended subject shall be constrained to at least have a reference or an identifier with at least a system and a value. | See [ci-fhir-stu3/issues/67](https://github.com/AuDigitalHealth/ci-fhir-stu3/issues/67)  |
|author | The design of this  element is incomplete. In the future it is intended author shall be constrained to at least have a reference or an identifier with at least a system and a value. | See [ci-fhir-stu3/issues/67](https://github.com/AuDigitalHealth/ci-fhir-stu3/issues/67)  |

...

## Additional context
composition-sml-prac-1 is an example of a Composition with these constraints in place including functioning FHIRPath expression.

**Comment by dbojicic-agency** [comment]
This issue has been addressed via adding known issues for the profile.
