### ISSUE TITLE
Event Summary Composition - invariant FHIRPaths are absolute and need to be relative

### ISSUE THREAD

**Issue by dtr-agency** [AuDigitalHealth/ci-fhir-stu3#68]
# Prerequisites

- [X] I have verified the problem exists in the available content
- [X] I have searched [open](https://github.com/ci-fhir-stu3/Issues/issues) and [closed](https://github.com/ci-fhir-stu3/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [X] I have written a descriptive issue title

# The bug
In composition-es-1 invariants inv-dh-cmp-02 to inv-dh-cmp-11 have FHIRPath expresssions written as absolute paths rather than relative.

At one point we had thought that absolute was necessary (in conjunction with some older IG Publisher behaviour) but this topic has been cleared up in the FHIR community. Invariant FHIRPath expressions are to be relative path. 

Invariants inv-dh-cmp-02 to inv-dh-cmp-11 need their FHIRPath converted to relative path and to be tested.

## What I expected to happen
N/A

## Steps to reproduce
N/A

## Screenshots
N/A

## Workarounds
This extant issue on the Event Summary Composition may be addressed in the STU3 profile by documentation of a known issue rather than adding invariants to the Composition. Or possibly a mix of both, addition of some invariants / constraints and a known issue covering off the other invariants not included in the STU3 profile.
Example known issue content

Example known issue content

| Reference | Description | Issue No. |
| ------------- | ------------- | ------------- |
| section(allergies) (invariants) | The FHIRPath expression for inv-dh-cmp-07 is written with an absolute path and it should be a relative path. The result of this is TBD. This issue will be fixed in an R4 variant of this profile. | See [ci-fhir-stu3/issues/68](https://github.com/AuDigitalHealth/ci-fhir-stu3/issues/68)  |

## QA.html excerpt
N/A

## Desktop (please complete the following information):
N/A

## Additional context
composition-sml-prac-1 is an example of a Composition with relative path invariants.

**Comment by robeastwood-agency** [comment]
Work is underway to implement the conversion of all composition profile invariant FHIRPaths from absolute to relative.

**Comment by robeastwood-agency** [comment]
This has been implemented via https://github.com/AuDigitalHealth/ci-fhir-stu3/commit/8fa64c59e0002fe6af45a11cb617eaef4f94740e

Specifically, the invariant FHIRPaths for these elements were converted to use relative paths:
- Composition.section inv-dh-cmp-07
- Composition.section:medications inv-dh-cmp-03
- Composition.section:medications inv-dh-cmp-08
- Composition.section:medicalHistory inv-dh-cmp-04
- Composition.section:medicalHistory inv-dh-cmp-09
- Composition.section:medicalHistory inv-dh-cmp-12
- Composition.section:immunisations inv-dh-cmp-05
- Composition.section:immunisations inv-dh-cmp-10
- Composition.section:immunisations inv-dh-cmp-11
