### ISSUE TITLE
Shared Health Summary Summary Composition - invariant FHIRPaths are absolute and need to be relative

### ISSUE THREAD

**Issue by dtr-agency** [AuDigitalHealth/ci-fhir-stu3#69]
# Prerequisites

- [X] I have verified the problem exists in the available content
- [X] I have searched [open](https://github.com/ci-fhir-stu3/Issues/issues) and [closed](https://github.com/ci-fhir-stu3/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [X] I have written a descriptive issue title

# The bug
In composition-shs-1 invariants inv-dh-cmp-02 to inv-dh-cmp-08 have FHIRPath expresssions written as absolute paths rather than relative.

At one point we had thought that absolute was necessary (in conjunction with some older IG Publisher behaviour) but this topic has been cleared up in the FHIR community. Invariant FHIRPath expressions are to be relative path. 

Invariants inv-dh-cmp-02 to inv-dh-cmp-08 need their FHIRPath converted to relative path and to be tested.

## What I expected to happen
N/A

## Steps to reproduce
N/A

## Screenshots
N/A

## Workarounds
This extant issue on the Shared Health Summary Composition may be addressed in the STU3 profile by documentation of a known issue rather than adding invariants to the Composition. Or possibly a mix of both, addition of some invariants / constraints and a known issue covering off the other invariants not included in the STU3 profile.
Example known issue content

Example known issue content

| Reference | Description | Issue No. |
| ------------- | ------------- | ------------- |
| section(allergies) (invariants) | The FHIRPath expression for inv-dh-cmp-02 is written with an absolute path and it should be a relative path. The result of this is TBD. This issue will be fixed in an R4 variant of this profile. | See [ci-fhir-stu3/issues/69](https://github.com/AuDigitalHealth/ci-fhir-stu3/issues/69)  |

## QA.html excerpt
N/A

## Desktop (please complete the following information):
N/A

## Additional context
composition-sml-prac-1 is an example of a Composition with relative path invariants.

**Comment by dbojicic-agency** [comment]
Work is underway to implement the conversion of all composition profile invariant FHIRPaths from absolute to relative.

**Comment by dbojicic-agency** [comment]
FHIRPath expressions for these elements were updated to use relative paths:
- Composition.section
   - inv-dh-cmp-02
- Composition.section:medications
   - inv-dh-cmp-03
    - inv-dh-cmp-04 
- Composition.medicalHistory
   - inv-dh-cmp-05
   - inv-dh-cmp-06
- Composition.immunisations
   - inv-dh-cmp-07
   - inv-dh-cmp-08
