### ISSUE TITLE
Provenance for the Generation of a List : agent slice bugs

### ISSUE THREAD

**Issue by dtr-agency** [AuDigitalHealth/ci-fhir-stu3#72]
# Prerequisites

- [ ] I have verified the problem exists in the available content
- [ ] I have searched [open](https://github.com/ci-fhir-stu3/Issues/issues) and [closed](https://github.com/ci-fhir-stu3/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [ ] I have written a descriptive issue title

# The bug
Some design issues are present here:
* The agent element should not have must support only on the defined slices do we want to set must support
* The "agent:All Slices" slice is not an intended slice - it should be removed

## What I expected to happen
N/A

## Steps to reproduce
N/A

## Screenshots
N/A

## Workarounds
This extant issue on the Provenance for the Generation of a List may be addressed in the STU3 profile by documentation of a known issue rather than fixing the slices in the List. 

| Reference | Description | Issue No. |
| ------------- | ------------- | ------------- |
| agent (slicing) | The profile contains a slice 'agent:All Slices' that is not an intended design for this profile. The result of this is TBD. This issue will be fixed in an R4 variant of this profile. | See [ci-fhir-stu3/issues/72](https://github.com/AuDigitalHealth/ci-fhir-stu3/issues/72)  |

## QA.html excerpt
N/A

## Desktop (please complete the following information):
N/A

**Comment by davidmckillop-ADHA** [comment]
This issue has also been added as known issue to the profile provenance-list-gen-1. STU3 work has been ceased and any future work will continue with R4.
