### ISSUE TITLE
List of Prescription and or Dispense Records - extension authorRole and authorRelatedParty errors in invariants

### ISSUE THREAD

**Issue by dtr-agency** [AuDigitalHealth/ci-fhir-stu3#73]
# Prerequisites
- [x] I have verified the problem exists in the available content
- [x] I have searched [open](https://github.com/ci-fhir-stu3/Issues/issues) and [closed](https://github.com/ci-fhir-stu3/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [x] I have written a descriptive issue title

# The bug
In the List of Prescription and or Dispense Records list profile (list-pdl-1), the invariants on the following 2 extensions have faulty FHIRPath expressions, related to the use of 'conformsTo'. The consequence of which is that acceptable content for these elements always fails to be valid against these invariants.

### 1) Element: List.extension:authorRole
- key: inv-dh-lst-09
- Description: A practitioner role shall conform to PractitionerRole with Practitioner with Mandatory Identifier
- FHIRpath expression: `resolve().conformsTo($this='http://ns.electronichealth.net.au/ci/fhir/3.0/StructureDefinition/practitionerrole-withpractitionerident-1')` 
### 2) Element: List.extension:authorRelatedPerson
- key: inv-dh-lst-10
- Description: A related person shall conform to RelatedPerson with Mandatory Identifier
- FHIRpath expression: `resolve().conformsTo($this='http://ns.electronichealth.net.au/ci/fhir/3.0/StructureDefinition/relatedperson-ident-1')`  |

## What I expected to happen
Acceptable content for this element shall be valid against these invariants.
Unacceptable content for this element shall not be valid against these invariants.

## Screenshots
N/A

## Workarounds
This extant issue on the Event Summary Composition may be addressed in the STU3 profile by documentation of a known issue rather than adding invariants to the Composition. Or possibly a mix of both, addition of some invariants / constraints and a known issue covering off the other invariants not included in the STU3 profile.
Example known issue content

Example known issue content

| Reference | Description | Issue No. |
| ------------- | ------------- | ------------- |
| extension:authorRole (invariants) | Invariant inv-dh-lst-09 has a defect in the FHIRPath expression. When validating using this profile, an instance containing extension:authorRole with a reference to a resource may not behave as expected, for example conforming instances may fail. This issue will be fixed in an R4 variant of this profile. | See [ci-fhir-stu3/issues/73](https://github.com/AuDigitalHealth/ci-fhir-stu3/issues/73)  |

## QA.html excerpt
N/A

## Desktop (please complete the following information):
N/A

## Additional context
N/A

**Comment by davidmckillop-ADHA** [comment]
The invariant inv-dh-lst-09 should be merged into inv-dh-lst-04, so that it becomes the author role shall at least have a reference that conforms to PractitionerRole with Practitioner with Mandatory Identifier or an identifier with at least a system and a value. This issue will be fixed in an R4 variant of this profile.

**Comment by davidmckillop-ADHA** [comment]
The invariant inv-dh-lst-10 should be merged into inv-dh-lst-05, so that it becomes the authoring related person shall at least have a reference that conforms to RelatedPerson with Mandatory Identifier or an identifier with at least a system and a value. This issue will be fixed in an R4 variant of this profile.

**Comment by davidmckillop-ADHA** [comment]
Known issues have been added to the 'List of Prescription and or Dispense Records' profile.
