### ISSUE TITLE
Device profiles (device-dh-base-1, device-ident-1, device-paid-1) - missing invariants on elements with a Reference

### ISSUE THREAD

**Issue by davidmckillop-ADHA** [AuDigitalHealth/ci-fhir-stu3#75]
# Prerequisites
- [X] I have searched [open](https://github.com/ci-fhir-stu3/Issues/issues) and [closed](https://github.com/ci-fhir-stu3/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already requested or reported
- [X] I have written a descriptive issue title

# The issue / feature
## Change description
The Device profiles are missing constraints on elements with a logical type of Reference. 

Without a constraint on Reference there is a wide range of values that are accepted as passing validation, some of which are undesirable. For example,
* if no further constraint is placed on Reference then a patient with only an extension is allowed - more permissible than we intend.

Add constraints on Composition elements of type Reference where additional constraints are desired for the use case:

This is expected to be:

Adding invariants at the Device element for:
Device.patient to enforce a reference shall at least have a reference, an identifier or a display
Device.owner to enforce a reference shall at least have a reference, an identifier or a display

## What it actually enables people to do
Enables consistent implementation and validation of meaningful data that serves the use case. Provides clarification of how to support the expected usage scenarios.

## Mockups 
Not available.

## How awesome would it be?
Highly desirable - the design is incomplete without these constraints. This issue must addressed at some stage prior to release for implementation.

## Workarounds
This missing design feature may be addressed in the STU3 profile by documentation of a known issue rather than adding invariants to the Device profiles. 

Example known issue content

| Reference | Description | Issue No. |
| ------------- | ------------- | ------------- |
| patient | The design of this element is incomplete. In the future it is intended a patient shall be constrained to at least have a reference or an identifier or a display. | See [ci-fhir-stu3/issues/75](https://github.com/AuDigitalHealth/ci-fhir-stu3/issues/75)  |
|owner | The design of this  element is incomplete. In the future it is intended an owner shall be constrained to at least have a reference or an identifier or a display. | See [ci-fhir-stu3/issues/75](https://github.com/AuDigitalHealth/ci-fhir-stu3/issues/75)  |

...

## Additional context
device-dh-base-1, device-ident-1, device-paid-1 are examples of a Device.patient and Device.owner where the constrainsts need to be added.

**Comment by davidmckillop-ADHA** [comment]
This issue has also been added as known issue to the profiles device-dh-base-1, device-ident-1, device-paid-1. STU3 work has been ceased and any future work will continue with R4.

**Comment by dtr-agency** [comment]
This issue is closed as the only implementation guide using these profiles is the PDL implementation guide which is now frozen.
