### ISSUE TITLE
Medicine Item Statement (StructureDefinition-medicationstatement-detailed-1) :: conditionally relax MedicationStatement.dosage cardinality 

### ISSUE THREAD

**Issue by dbojicic-agency** [AuDigitalHealth/ci-fhir-stu3#76]
# Prerequisites
- [x] I have searched [open](https://github.com/ci-fhir-stu3/Issues/issues) and [closed](https://github.com/ci-fhir-stu3/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already requested or reported
- [x] I have written a descriptive issue title

# The issue / feature
## Change description
The profile '_Medicine Item Statement_' (medicationstatement-detailed-1) mandates the MedicationStatement.dosage for a medicine item regardless of its status.
In order to support Pharmacist Shared Medicine List (PSML) that strictly prohibits dosage information for all ceased medicine items, MedicationStatement.dosage cardinality should be relaxed to 0..*, with a rule to require this element for all active medicine items. 

## What it actually enables people to do
Instances of MedicationStatement complying to this profile can bit don't have to supply dosage information for medicine items with a status  other than 'active' or 'intended'.,

## How awesome would it be?
This change allows greater implementer flexibility and increases number of use cases for the profile.  

## Workarounds
nil

## Additional context
nil

**Comment by robeastwood-agency** [comment]
Changes to the profile are now in peer review

**Comment by robeastwood-agency** [comment]
Work on the profile has been completed (relaxed the dosage constraint from 1..* to 0..* and added invariant to ensure that if the status is active or intended, then dosage shall be provided). See commit https://github.com/AuDigitalHealth/ci-fhir-stu3/commit/1b42195a01b0d1fc63ec394b36aac54953193565

Changes to supporting files forthcoming.

**Comment by dtr-agency** [comment]
@robeastwood-agency
